<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/we-codes/image/upload/v1554390254/cover.jpg" alt="Aniekan Edet">
                        <h6>Aniekan Edet</h6>
                        <p>Frontend Developer</p>
                        <ul class="list">
                        <li><a href="https://twitter.com/aniekanedett" target="_blank"<i class="fab fa-twitter"></i></a></li>
                        <li><a href="https://github.com/aniekanedet" target="_blank"<i class="fab fa-github"></i></a></li>
                        <li><a href="https://medium.com/@aniekanedet" target="_blank"<i class="fab fa-medium"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hi! I'm aniekan edet a Frontend dev. <br> with 3 years expereince, bulding solutions for businesses <br> and personal brands </p>
                        <br />
                        <h6>Skills</h6>
                        <p>HTML | CSS | Bootstrap | JavaScript | VUE | Wordpress </p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
